package dicetester;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author 507606
 */
public class YatzheeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form YatzheeJFrame
     */
    
    //game state constants
    public final static int RESET_GAME = 0;
    public final static int BEFORE_1ST_ROLL = 1;
    public final static int BEFORE_2ND_ROLL = 2;
    public final static int BEFORE_3RD_ROLL = 3;
    public final static int AFTER_3RD_ROLL = 4;
    public final static int SCORING = 5;
    public final static int GAME_OVER = 6;
    
    // lower score category constants 
    public final static int THREE_OF_A_KIND = 0;
    public final static int FOUR_OF_A_KIND = 1;
    public final static int FULL_HOUSE = 2;
    public final static int SMALL_STRAIGHT = 3;
    public final static int LARGE_STRAIGHT = 4;
    public final static int YATZHEE = 5;
    public final static int CHANCE = 6;
    
    
    //dice state constants
    public static final int NUM_DICE = 5;
    public static final int NUM_SIDES = 6;
    

            
    public YatzheeJFrame() 
    {
        initComponents();
        
        //create buttons array.
        //create array of dice that you want to hold.
        holdButtonArray = new JToggleButton[NUM_DICE];
        holdArray = new boolean[NUM_DICE];
        holdButtonArray[0] = holdButtonOne;
        holdButtonArray[1] = holdButtonTwo;
        holdButtonArray[2] = holdButtonThree;
        holdButtonArray[3] = holdButtonFour;
        holdButtonArray[4] = holdButtonFive;    
        myDice = new Dice (NUM_DICE,NUM_SIDES);
        
        
        //TMP SHOULD BE RESET GAME.
        manageUIState(BEFORE_1ST_ROLL);
    }
    
    public void manageUIState(int nextState)
    {
        switch (nextState)
        {
            case RESET_GAME:
                //todo
                break; 
            case BEFORE_1ST_ROLL:
                //disable hold buttons, then enable roll button, and clear the hold array.
                
               clearAndDisableHoldButtons();
               
               rollButton.setEnabled(true);
               
               clearHoldArray();
               
                break;
            case BEFORE_2ND_ROLL:
                //now we can enable the hold button. 
                enableHoldButtons();
                break;
            case BEFORE_3RD_ROLL:
                break;
            case AFTER_3RD_ROLL:
                // we need to disable the roll button here. 
                rollButton.setEnabled(false);
                break;
            case SCORING:
                break;
            case GAME_OVER:
                break;   
            default:
                JOptionPane.showMessageDialog(this, "Uh Oh! Invalid UI state detected.");
                break;
        }
        currentUIState = nextState;
        
        
        
        
    }
    
    private void clearAndDisableHoldButtons()
    {
        for (int i = 0; i < holdButtonArray.length; i++)
        {
            holdButtonArray[i].setText("");
            holdButtonArray[i].setEnabled(false);
            holdButtonArray[i].setSelected(false);
        }
            
    }
    
    
    private void clearHoldArray()
    {
        for (int i = 0; i < holdArray.length; i++)
        {
            holdArray[i] = false;
        }
    }
    
    
    private void enableHoldButtons()
    {
        for (int i = 0; i < holdButtonArray.length; i++)
        {
            holdButtonArray[i].setEnabled(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton15 = new javax.swing.JToggleButton();
        holdButtonOne = new javax.swing.JToggleButton();
        rollButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        holdButtonFive = new javax.swing.JToggleButton();
        holdButtonThree = new javax.swing.JToggleButton();
        holdButtonFour = new javax.swing.JToggleButton();
        holdButtonTwo = new javax.swing.JToggleButton();
        acesButton = new javax.swing.JToggleButton();
        twosButton = new javax.swing.JToggleButton();
        foursButton = new javax.swing.JToggleButton();
        threesButton = new javax.swing.JToggleButton();
        fivesButton = new javax.swing.JToggleButton();
        sixesButton = new javax.swing.JToggleButton();
        threeOfAKindButton = new javax.swing.JToggleButton();
        fullHouseButton = new javax.swing.JToggleButton();
        smallstr8Button = new javax.swing.JToggleButton();
        largeStr8Button = new javax.swing.JToggleButton();
        fourOfAKindButton = new javax.swing.JToggleButton();
        chanceButton = new javax.swing.JToggleButton();
        yahtzeeButton = new javax.swing.JToggleButton();
        acesField = new javax.swing.JTextField();
        threesField = new javax.swing.JTextField();
        foursField = new javax.swing.JTextField();
        fivesField = new javax.swing.JTextField();
        twosField = new javax.swing.JTextField();
        sixesField = new javax.swing.JTextField();
        threeKindField = new javax.swing.JTextField();
        fourKindField = new javax.swing.JTextField();
        fullHouseField = new javax.swing.JTextField();
        smallStr8Field = new javax.swing.JTextField();
        largeStr8Field = new javax.swing.JTextField();
        yahtzeeField = new javax.swing.JTextField();
        chanceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        upperScoreField = new javax.swing.JTextField();
        bonusField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grandTotalField = new javax.swing.JTextField();
        totalLowerScoreField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalUpperScoreField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();

        jToggleButton15.setText("jToggleButton15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elijah's Yatzhee ");
        setSize(new java.awt.Dimension(300, 100));

        holdButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonOneActionPerformed(evt);
            }
        });

        rollButton.setText("Roll ");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        scoreButton.setText("Score");
        scoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreButtonActionPerformed(evt);
            }
        });

        holdButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonFiveActionPerformed(evt);
            }
        });

        holdButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonThreeActionPerformed(evt);
            }
        });

        holdButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonFourActionPerformed(evt);
            }
        });

        holdButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonTwoActionPerformed(evt);
            }
        });

        acesButton.setText("Aces");
        acesButton.setPreferredSize(new java.awt.Dimension(120, 40));

        twosButton.setText("Twos");

        foursButton.setText("Fours");
        foursButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursButtonActionPerformed(evt);
            }
        });

        threesButton.setText("Threes");

        fivesButton.setText("Fives");

        sixesButton.setText("Sixes");

        threeOfAKindButton.setText("3 of a Kind");
        threeOfAKindButton.setPreferredSize(new java.awt.Dimension(120, 40));

        fullHouseButton.setText("Full House");
        fullHouseButton.setPreferredSize(new java.awt.Dimension(115, 40));

        smallstr8Button.setText("Small Straight");
        smallstr8Button.setPreferredSize(new java.awt.Dimension(115, 40));

        largeStr8Button.setText("Large Straight");
        largeStr8Button.setPreferredSize(new java.awt.Dimension(115, 40));

        fourOfAKindButton.setText("4 of a Kind");
        fourOfAKindButton.setPreferredSize(new java.awt.Dimension(115, 40));

        chanceButton.setText("Chance");
        chanceButton.setPreferredSize(new java.awt.Dimension(115, 40));
        chanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceButtonActionPerformed(evt);
            }
        });

        yahtzeeButton.setText("Yahtzee!");
        yahtzeeButton.setPreferredSize(new java.awt.Dimension(115, 40));

        fivesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivesFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Not Yahtzee!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Bonus if >63:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Upper Score:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("Total Lower Score:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Grand Total:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Total Upper Score:");

        newGameButton.setText("Play Again?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fivesButton)
                                .addGap(18, 18, 18)
                                .addComponent(fivesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sixesButton)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upperScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sixesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bonusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalUpperScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foursButton)
                                .addGap(18, 18, 18)
                                .addComponent(foursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourOfAKindButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fourKindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(threeOfAKindButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(threeKindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fullHouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fullHouseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(smallstr8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(smallStr8Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largeStr8Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(largeStr8Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yahtzeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yahtzeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(chanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(grandTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalLowerScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(twosButton)
                                .addGap(18, 18, 18)
                                .addComponent(twosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(threesButton)
                                .addGap(18, 18, 18)
                                .addComponent(threesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newGameButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(holdButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(holdButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(holdButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(holdButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(holdButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {acesButton, fivesButton, foursButton, sixesButton, threesButton, twosButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chanceButton, fourOfAKindButton, fullHouseButton, largeStr8Button, smallstr8Button, threeOfAKindButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {holdButtonFive, holdButtonFour, holdButtonOne, holdButtonThree, holdButtonTwo, rollButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(holdButtonOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(holdButtonFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(holdButtonTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(holdButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holdButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeOfAKindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeKindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twosButton)
                    .addComponent(fourOfAKindButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourKindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threesButton)
                    .addComponent(fullHouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullHouseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foursButton)
                    .addComponent(smallstr8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallStr8Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fivesButton)
                    .addComponent(largeStr8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largeStr8Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yahtzeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yahtzeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upperScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(totalLowerScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(grandTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalUpperScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGameButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {acesButton, fivesButton, foursButton, sixesButton, threesButton, twosButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chanceButton, fourOfAKindButton, fullHouseButton, largeStr8Button, smallstr8Button, threeOfAKindButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {holdButtonFive, holdButtonFour, holdButtonOne, holdButtonThree, holdButtonTwo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed

        for (int i = 0; i < NUM_DICE; i++)
        {
            //if user isnt holding die, roll.
            if (!holdArray[i])
            {
                myDice.rollDie(i);
                holdButtonArray[i].setText("" + myDice.getDieValue(i));
            }
        }   
        
       if (currentUIState == BEFORE_1ST_ROLL)
       {
           manageUIState(BEFORE_2ND_ROLL);
       }
       else if (currentUIState == BEFORE_2ND_ROLL)
       {
           manageUIState(BEFORE_3RD_ROLL);
       }
       else if (currentUIState == BEFORE_3RD_ROLL)
       {
           manageUIState(AFTER_3RD_ROLL);
       }
       
    }//GEN-LAST:event_rollButtonActionPerformed

    private void scoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreButtonActionPerformed
        //tmp need to test for last turn
        manageUIState(BEFORE_1ST_ROLL);
            
    }//GEN-LAST:event_scoreButtonActionPerformed

    private void holdButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonOneActionPerformed
        // TODO add your handling code here:
        holdArray[0] = !holdArray[0];
    }//GEN-LAST:event_holdButtonOneActionPerformed

    private void holdButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonTwoActionPerformed
        // TODO add your handling code here:
        holdArray[1] = !holdArray[1];
    }//GEN-LAST:event_holdButtonTwoActionPerformed

    private void holdButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonThreeActionPerformed
        // TODO add your handling code here:
        holdArray[2] = !holdArray[2];
    }//GEN-LAST:event_holdButtonThreeActionPerformed

    private void holdButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonFourActionPerformed
        // TODO add your handling code here:
        holdArray[3] = !holdArray[3];
    }//GEN-LAST:event_holdButtonFourActionPerformed

    private void holdButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonFiveActionPerformed
        // TODO add your handling code here:
        holdArray[4] = !holdArray[4];
    }//GEN-LAST:event_holdButtonFiveActionPerformed

    private void foursButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foursButtonActionPerformed

    private void chanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chanceButtonActionPerformed

    private void fivesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fivesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YatzheeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YatzheeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YatzheeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YatzheeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YatzheeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton acesButton;
    private javax.swing.JTextField acesField;
    private javax.swing.JTextField bonusField;
    private javax.swing.JToggleButton chanceButton;
    private javax.swing.JTextField chanceField;
    private javax.swing.JToggleButton fivesButton;
    private javax.swing.JTextField fivesField;
    private javax.swing.JTextField fourKindField;
    private javax.swing.JToggleButton fourOfAKindButton;
    private javax.swing.JToggleButton foursButton;
    private javax.swing.JTextField foursField;
    private javax.swing.JToggleButton fullHouseButton;
    private javax.swing.JTextField fullHouseField;
    private javax.swing.JTextField grandTotalField;
    private javax.swing.JToggleButton holdButtonFive;
    private javax.swing.JToggleButton holdButtonFour;
    private javax.swing.JToggleButton holdButtonOne;
    private javax.swing.JToggleButton holdButtonThree;
    private javax.swing.JToggleButton holdButtonTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton largeStr8Button;
    private javax.swing.JTextField largeStr8Field;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton rollButton;
    private javax.swing.JButton scoreButton;
    private javax.swing.JToggleButton sixesButton;
    private javax.swing.JTextField sixesField;
    private javax.swing.JTextField smallStr8Field;
    private javax.swing.JToggleButton smallstr8Button;
    private javax.swing.JTextField threeKindField;
    private javax.swing.JToggleButton threeOfAKindButton;
    private javax.swing.JToggleButton threesButton;
    private javax.swing.JTextField threesField;
    private javax.swing.JTextField totalLowerScoreField;
    private javax.swing.JTextField totalUpperScoreField;
    private javax.swing.JToggleButton twosButton;
    private javax.swing.JTextField twosField;
    private javax.swing.JTextField upperScoreField;
    private javax.swing.JToggleButton yahtzeeButton;
    private javax.swing.JTextField yahtzeeField;
    // End of variables declaration//GEN-END:variables
    private Dice myDice; 
   
    private JToggleButton[] holdButtonArray;
    private JToggleButton[] upperScoreButtonArray;
    private JToggleButton[] lowerScoreButtonArray;
    private JTextField[] upperScoreTextBoxArray;
    private JTextField[] lowerScoreTextBoxArray;
    private boolean[] holdArray;
    private int rollNum; // TMP VAR
    private int currentUIState;
   // private GameModel game;

}

